#pragma once
#include <SFML/Graphics.hpp>
#include <iostream>
#include <string>
#include <fstream>
#include "../include/Piece.hpp"
#include "../include/Pawn.hpp"
#include "../include/King.hpp"
#include "../include/Bishop.hpp"
#include "../include/Knight.hpp"
#include "../include/Queen.hpp"
#include "../include/Rook.hpp"
#include "../include/Game.hpp"
